jaffle_shop:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      keyfile: /Users/kennethning/dbt-tutorial-314920-74c34d1c46f0.json
      project: dbt-tutorial-314920
      dataset: dbt_prod
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive